version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: flowsync-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: flowsync-backend
    ports:
      - "5001:5000"
    env_file: ./backend/.env  
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: flowsync-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
